/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_user (void)
{
  GtkWidget *ajout_user;
  GtkWidget *fixed1;
  GtkWidget *entryNom_user;
  GtkWidget *entryPrenom_user;
  GtkWidget *entryCin_user;
  GtkObject *spinbuttonJour_user_adj;
  GtkWidget *spinbuttonJour_user;
  GtkObject *spinbuttonMois_user_adj;
  GtkWidget *spinbuttonMois_user;
  GtkObject *spinbuttonAnnee_user_adj;
  GtkWidget *spinbuttonAnnee_user;
  GtkObject *spinbuttonNumBV_user_adj;
  GtkWidget *spinbuttonNumBV_user;
  GtkObject *spinbuttonVote_user_adj;
  GtkWidget *spinbuttonVote_user;
  GtkWidget *entryProf_user;
  GtkWidget *radiobuttonFemme_user;
  GSList *radiobuttonFemme_user_group = NULL;
  GtkWidget *radiobuttonHomme_user;
  GtkWidget *checkbuttonEtranger_user;
  GtkWidget *checkbuttonTun_user;
  GtkWidget *buttonAfficher_user;
  GtkWidget *buttonValider_user;
  GtkWidget *comboboxRole_user;
  GtkWidget *comboboxApp_user;

  ajout_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_user), _("window1"));
  gtk_window_set_default_size (GTK_WINDOW (ajout_user), 600, 400);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajout_user), fixed1);

  entryNom_user = gtk_entry_new ();
  gtk_widget_show (entryNom_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom_user, 144, 32);
  gtk_widget_set_size_request (entryNom_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom_user), 8226);

  entryPrenom_user = gtk_entry_new ();
  gtk_widget_show (entryPrenom_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPrenom_user, 144, 72);
  gtk_widget_set_size_request (entryPrenom_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom_user), 8226);

  entryCin_user = gtk_entry_new ();
  gtk_widget_show (entryCin_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entryCin_user, 160, 200);
  gtk_widget_set_size_request (entryCin_user, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryCin_user), 8);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCin_user), 8226);

  spinbuttonJour_user_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonJour_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJour_user_adj), 1, 0);
  gtk_widget_show (spinbuttonJour_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonJour_user, 144, 136);
  gtk_widget_set_size_request (spinbuttonJour_user, 60, 27);

  spinbuttonMois_user_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonMois_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_user_adj), 1, 0);
  gtk_widget_show (spinbuttonMois_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonMois_user, 240, 136);
  gtk_widget_set_size_request (spinbuttonMois_user, 60, 27);

  spinbuttonAnnee_user_adj = gtk_adjustment_new (1, 1800, 2004, 1, 10, 10);
  spinbuttonAnnee_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnee_user_adj), 1, 0);
  gtk_widget_show (spinbuttonAnnee_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonAnnee_user, 336, 136);
  gtk_widget_set_size_request (spinbuttonAnnee_user, 60, 27);

  spinbuttonNumBV_user_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonNumBV_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNumBV_user_adj), 1, 0);
  gtk_widget_show (spinbuttonNumBV_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonNumBV_user, 184, 376);
  gtk_widget_set_size_request (spinbuttonNumBV_user, 60, 27);

  spinbuttonVote_user_adj = gtk_adjustment_new (1, -1, 1, 1, 10, 10);
  spinbuttonVote_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonVote_user_adj), 1, 0);
  gtk_widget_show (spinbuttonVote_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonVote_user, 184, 456);
  gtk_widget_set_size_request (spinbuttonVote_user, 60, 27);

  entryProf_user = gtk_entry_new ();
  gtk_widget_show (entryProf_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entryProf_user, 232, 616);
  gtk_widget_set_size_request (entryProf_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryProf_user), 8226);

  radiobuttonFemme_user = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonFemme_user);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonFemme_user, 312, 320);
  gtk_widget_set_size_request (radiobuttonFemme_user, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonFemme_user), radiobuttonFemme_user_group);
  radiobuttonFemme_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonFemme_user));

  radiobuttonHomme_user = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonHomme_user);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonHomme_user, 168, 320);
  gtk_widget_set_size_request (radiobuttonHomme_user, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonHomme_user), radiobuttonFemme_user_group);
  radiobuttonFemme_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonHomme_user));

  checkbuttonEtranger_user = gtk_check_button_new_with_mnemonic (_("Etrangere"));
  gtk_widget_show (checkbuttonEtranger_user);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbuttonEtranger_user, 352, 552);
  gtk_widget_set_size_request (checkbuttonEtranger_user, 118, 24);

  checkbuttonTun_user = gtk_check_button_new_with_mnemonic (_("Tunisienne"));
  gtk_widget_show (checkbuttonTun_user);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbuttonTun_user, 184, 544);
  gtk_widget_set_size_request (checkbuttonTun_user, 118, 24);

  buttonAfficher_user = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (buttonAfficher_user);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAfficher_user, 560, 552);
  gtk_widget_set_size_request (buttonAfficher_user, 136, 40);

  buttonValider_user = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (buttonValider_user);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonValider_user, 552, 640);
  gtk_widget_set_size_request (buttonValider_user, 152, 40);

  comboboxRole_user = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxRole_user);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxRole_user, 168, 248);
  gtk_widget_set_size_request (comboboxRole_user, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("observateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("electeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("agentBV"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("autres"));

  comboboxApp_user = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxApp_user);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxApp_user, 232, 664);
  gtk_widget_set_size_request (comboboxApp_user, 205, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxApp_user), _("gauche"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxApp_user), _("droite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxApp_user), _("autres"));

  g_signal_connect ((gpointer) radiobuttonFemme_user, "toggled",
                    G_CALLBACK (on_radiobuttonFemme_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonHomme_user, "toggled",
                    G_CALLBACK (on_radiobuttonHomme_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonEtranger_user, "toggled",
                    G_CALLBACK (on_checkbuttonEtranger_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonTun_user, "toggled",
                    G_CALLBACK (on_checkbuttonTun_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficher_user, "clicked",
                    G_CALLBACK (on_buttonAfficher_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonValider_user, "clicked",
                    G_CALLBACK (on_buttonValider_user_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_user, ajout_user, "ajout_user");
  GLADE_HOOKUP_OBJECT (ajout_user, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_user, entryNom_user, "entryNom_user");
  GLADE_HOOKUP_OBJECT (ajout_user, entryPrenom_user, "entryPrenom_user");
  GLADE_HOOKUP_OBJECT (ajout_user, entryCin_user, "entryCin_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonJour_user, "spinbuttonJour_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonMois_user, "spinbuttonMois_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonAnnee_user, "spinbuttonAnnee_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonNumBV_user, "spinbuttonNumBV_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonVote_user, "spinbuttonVote_user");
  GLADE_HOOKUP_OBJECT (ajout_user, entryProf_user, "entryProf_user");
  GLADE_HOOKUP_OBJECT (ajout_user, radiobuttonFemme_user, "radiobuttonFemme_user");
  GLADE_HOOKUP_OBJECT (ajout_user, radiobuttonHomme_user, "radiobuttonHomme_user");
  GLADE_HOOKUP_OBJECT (ajout_user, checkbuttonEtranger_user, "checkbuttonEtranger_user");
  GLADE_HOOKUP_OBJECT (ajout_user, checkbuttonTun_user, "checkbuttonTun_user");
  GLADE_HOOKUP_OBJECT (ajout_user, buttonAfficher_user, "buttonAfficher_user");
  GLADE_HOOKUP_OBJECT (ajout_user, buttonValider_user, "buttonValider_user");
  GLADE_HOOKUP_OBJECT (ajout_user, comboboxRole_user, "comboboxRole_user");
  GLADE_HOOKUP_OBJECT (ajout_user, comboboxApp_user, "comboboxApp_user");

  return ajout_user;
}

GtkWidget*
create_affichage_user (void)
{
  GtkWidget *affichage_user;
  GtkWidget *fixed2;
  GtkWidget *fixed3;
  GtkWidget *treeview_user;
  GtkWidget *entryRechercher_user;
  GtkWidget *label1;
  GtkWidget *buttonEnregistrer_user;
  GtkWidget *buttonAjouter_user;
  GtkWidget *buttonModifier_user;
  GtkWidget *buttonSupprimer_user;
  GtkWidget *buttonRechercher_user;

  affichage_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage_user), _("window2"));
  gtk_window_set_default_size (GTK_WINDOW (affichage_user), 600, 400);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (affichage_user), fixed2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed3, 136, 216);
  gtk_widget_set_size_request (fixed3, 50, 50);

  treeview_user = gtk_tree_view_new ();
  gtk_widget_show (treeview_user);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_user, 24, 80);
  gtk_widget_set_size_request (treeview_user, 1384, 648);

  entryRechercher_user = gtk_entry_new ();
  gtk_widget_show (entryRechercher_user);
  gtk_fixed_put (GTK_FIXED (fixed2), entryRechercher_user, 96, 24);
  gtk_widget_set_size_request (entryRechercher_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRechercher_user), 8226);

  label1 = gtk_label_new (_("Cin :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 24, 32);
  gtk_widget_set_size_request (label1, 41, 17);

  buttonEnregistrer_user = gtk_button_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (buttonEnregistrer_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonEnregistrer_user, 1456, 736);
  gtk_widget_set_size_request (buttonEnregistrer_user, 96, 32);

  buttonAjouter_user = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonAjouter_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjouter_user, 1464, 224);
  gtk_widget_set_size_request (buttonAjouter_user, 80, 32);

  buttonModifier_user = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonModifier_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonModifier_user, 1472, 280);
  gtk_widget_set_size_request (buttonModifier_user, 88, 32);

  buttonSupprimer_user = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttonSupprimer_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSupprimer_user, 1480, 344);
  gtk_widget_set_size_request (buttonSupprimer_user, 88, 32);

  buttonRechercher_user = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (buttonRechercher_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonRechercher_user, 320, 24);
  gtk_widget_set_size_request (buttonRechercher_user, 120, 32);

  g_signal_connect ((gpointer) treeview_user, "row_activated",
                    G_CALLBACK (on_treeview_user_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonEnregistrer_user, "clicked",
                    G_CALLBACK (on_buttonEnregistrer_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouter_user, "clicked",
                    G_CALLBACK (on_buttonAjouter_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier_user, "clicked",
                    G_CALLBACK (on_buttonModifier_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimer_user, "clicked",
                    G_CALLBACK (on_buttonSupprimer_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercher_user, "clicked",
                    G_CALLBACK (on_buttonRechercher_user_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage_user, affichage_user, "affichage_user");
  GLADE_HOOKUP_OBJECT (affichage_user, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (affichage_user, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (affichage_user, treeview_user, "treeview_user");
  GLADE_HOOKUP_OBJECT (affichage_user, entryRechercher_user, "entryRechercher_user");
  GLADE_HOOKUP_OBJECT (affichage_user, label1, "label1");
  GLADE_HOOKUP_OBJECT (affichage_user, buttonEnregistrer_user, "buttonEnregistrer_user");
  GLADE_HOOKUP_OBJECT (affichage_user, buttonAjouter_user, "buttonAjouter_user");
  GLADE_HOOKUP_OBJECT (affichage_user, buttonModifier_user, "buttonModifier_user");
  GLADE_HOOKUP_OBJECT (affichage_user, buttonSupprimer_user, "buttonSupprimer_user");
  GLADE_HOOKUP_OBJECT (affichage_user, buttonRechercher_user, "buttonRechercher_user");

  return affichage_user;
}

